name: Build LaTeX Document

on:
  push:
    paths:
      - "report/main.tex"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup LaTeX
        run: |
          sudo apt-get install -y texlive-xetex
        continue-on-error: true

      - name: Build PDF
        run: |
          cd report
          xelatex -interaction=nonstopmode -halt-on-error main.tex
          xelatex -interaction=nonstopmode -halt-on-error main.tex
        continue-on-error: true

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: main.pdf
          path: report/main.pdf
